/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bryanmarty_javawifi_SystemInterface */

#ifndef _Included_com_bryanmarty_javawifi_SystemInterface
#define _Included_com_bryanmarty_javawifi_SystemInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetAllInterfaceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetAllInterfaceNames
  (JNIEnv *, jclass);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetAllWiFiInterfaceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetAllWiFiInterfaceNames
  (JNIEnv *, jclass);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceIsWiFi
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceIsWiFi
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetSSID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetSSID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetNickname
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetNickname
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetHardwareAddress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetHardwareAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetFrequency
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetFrequency
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceGetBitRate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetBitRate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceIsCableConnected
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceIsCableConnected
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
