/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bryanmarty_javawifi_SystemInterface */

#ifndef _Included_com_bryanmarty_javawifi_SystemInterface
#define _Included_com_bryanmarty_javawifi_SystemInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bryanmarty_javawifi_SystemInterface
 * Method:    nativeInterfaceIsWiFi
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceIsWiFi
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetSSID
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_bryanmarty_javawifi_SystemInterface_nativeInterfaceGetHardwareAddress
  (JNIEnv * env, jobject obj, jstring interfaceName);

#ifdef __cplusplus
}
#endif
#endif
